---
title: Ideas for the workshop
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---
***

#### 1. Brief Introduction for Meetup

Este workshop é para todas e todos os que querem aprender R ou actualizar alguns conceitos básicos de R e partilhar conhecimento também! Será possível começar logo a programar em R e a produzir alguns exemplos úteis de visualização de dados. Este é o primeiro passo para te motivar a aprender mais sobre dados e a contar boas histórias com os mesmos.

***

This workshop is for who wants to learn R or refresh some basic concepts in R and share some knowledge too! You'll be able to start right away with the R language and produce some useful data visualizations. This is a first step to motivate you to understand more about data and tell good stories with it.


#### 2. Useful links

* https://www.thinkwithgoogle.com/articles/tell-meaningful-stories-with-data.html
* http://www.thinkwithgoogle.com/articles/data-stories.html
* https://www.thinkwithgoogle.com/articles/data-to-insights-blueprint-for-your-business.html


#### **3. Instructions pre-workshop**

<span style = "color: green"> Add instructions to download R and install R studio</span>

# Instalação de R e R-Studio ***(Installing R and R-Studio)***

Para participar activamente no segundo workshop do R-Ladies (‘Visualização de Dados’), deve trazer consigo um computador portátil. Para que o computador execute código em R é necessário: 

 - instalar R
 
 - instalar R-Studio.
 
As instruções que se seguem explicam como fazer estas duas instalações em computadores com sistema operativo Mac ou Windows.

***To actively participate in the second workshop of R-Ladies (‘Data Visualization’) you must bring a laptop. To be able to execute R code in the laptop you have to:***

 ***- install R*** 
 
 ***- install R-Studio***
 
***The following instructions explain how to perform these 2 installations in computers with Mac and Windows operating systems.***

## Instalar R e R-Studio num Mac ***(Install R and R-Studio for Mac)***

Os links seguintes contêm vídeos que explicam como instalar R e R-studio num Mac:

https://www.youtube.com/watch?v=uxuuWXU-7UQ (R)

https://www.youtube.com/watch?v=JbTMvQ-SbvQ (R-Studio)

Em alternativa, pode simplesmente guiar-se pelas seguintes instruções.

***The following links contain videos guiding you to install R and R-Studio for Mac:***

***https://www.youtube.com/watch?v=uxuuWXU-7UQ (R)***

***https://www.youtube.com/watch?v=JbTMvQ-SbvQ (R-Studio)***

***In alternative to the videos, you can simply follow the instructions below.***

### Instalar R ***(Install R)***
Abra o browser da web e vá à página do CRAN (Comprehensive R Archive Network):

https://cran.r-project.org/

Verá que há várias alternativas de download para diferentes plataformas. Clique em "Download R for (Mac) OS X". Em seguida clique em "R-3.3.2.pkg" e espere que o download esteja completo.

Quando o download terminar, abra o documento descarregado. Isto iniciará o instalador. Siga simplesmente as instruções do instalador e aceite as definições pré-estabelecidas.

***Open your web browser and go to CRAN (Comprehensive R Archive Network):***

***https://cran.r-project.org/***

***You'll see that there are a number of options of download for different platforms. Click on "Download R for (Mac) OS X". Then click on "R-3.3.2.pkg" and wait for the download to complete.***
 
***Once it's finished downloading, open up the package. This will start the installer. Just follow the instructions of the installer and accept the default settings.***

### Instalar R-Studio ***(Install R-Studio)***
É importante notar que só é possível instalar o R-Studio no seu computador se já tiver préviamente instalado o R. Depois de instalar R, abra o browser da web e vá à página do R-Studio:

https://www.rstudio.com/products/rstudio/download/

Deslize para o fim da página onde diz **"Installers for Supported Platforms"** e clique em **"RStudio 1.0.136 - Mac OS X 10.6+ (64-bit)"**. 

Quando o download estiver completo, vá à pasta ‘Downloads’ e clique 2-vezes no ficheiro descarregado. Isto deverá iniciar o instalador. Basta seguir as instruções do instalador e aceitas as definições pré-estabelecidas.

Como em qualquer aplicação para Mac, é necessário colocar o shortcut do R-Studio na pasta ‘Aplicações’. Para iniciar R-Studio só precisa de ir à pasta ‘Aplicações’ e clicar 2-vezes em R-Studio.

***It is important to note that you need to have R already installed in your computer to be able to install R-Studio. Once you have installed R, open your web browser and go to the website of R-Studio:***

***https://www.rstudio.com/products/rstudio/download/***

***Scroll down to the end of the page where it says "Installers for Supported Platforms" and click "RStudio 1.0.136 - Mac OS X 10.6+ (64-bit)".*** 

***Once the download is complete, go to the ‘Downloads’ folder and click on the downloaded file. This should start the installer. Simply follow the instructions and accept the default parameters.***

***Just like any other Mac application, you need to drag the R-Studio shortcut into the ‘Applications’ folder.***

***To start R-Studio, just go to the applications folder and double on R-Studio.***


## Instalar R e R-Studio num Windows ***(Install R and R-Studio for Windows)***

O link seguinte contém um video que explica como instalar R e R-studio em Windows:

https://www.youtube.com/watch?v=5ZbjUEg4a1g

Em alternativa, pode simplesmente guiar-se pelas seguintes instruções.

***A video to guide you in the installation of R and R-Studio for Windows can be found here:***

***https://www.youtube.com/watch?v=5ZbjUEg4a1g***

***In alternative to the video, you can simply follow the instructions below.***


### Instalar R ***(Install R)***
Abra o browser da web e vá à página do CRAN (Comprehensive R Archive Network):

https://cran.r-project.org/

Verá que há várias alternativas de download para diferentes plataformas. Será direccionado para uma nova página, onde deverá clicar em ‘base’. Na página seguinte, clique em ‘Download R 3.3.2 for Windows’.

Quando o download terminar, abra o documento descarregado. Isto iniciará o instalador. Siga simplesmente as instruções do instalador e aceite as definições pré-estabelecidas.

***Open your web browser and go to CRAN (Comprehensive R Archive Network):***

***https://cran.r-project.org/***

***You'll see that there are a number of options for you to download here for different platforms. Click on the option for Windows.*** 

 ***You’ll be directed to the following window, where you have to click on ‘base’. On the next page click on ‘Download R 3.3.2 for Windows’.*** 

***Once it's finished downloading, open up the package. This will start the installer. Just follow the instructions of the installer and accept the default parameters.***


### Instalar R-Studio ***(Install R-Studio)***

É importante notar que só é possível instalar o R-Studio no seu computador se já tiver préviamente instalado o R. Depois de instalar R, abra o browser da web e vá à página do R-Studio:

https://www.rstudio.com/products/rstudio/download/

Deslize para o fim da pagina onde diz "Installers for Supported Platforms" e clique em "RStudio 1.0.136 - Windows Vista/7/8/10". 

Quando o download estiver completo, vá à pasta ‘Downloads’ e clique 2-vezes no ficheiro descarregado. Isto deverá iniciar o instalador. Basta seguir as instruções do instalador e aceitar as definições pré-estabelecidas.

***It is important to note that you need to have R already installed in your computer to be able to install R-Studio. Open your web browser and go to the website of R-Studio:***

***https://www.rstudio.com/***

***Scroll down to the end of the page where it says "Installers for Supported Platforms" and click "RStudio 1.0.136 - Windows Vista/7/8/10".*** 

***Once the download is complete, open the downloaded file. This should start the installation. Simply follow the instructions in the installer and accept the default parameters.***




#### **4. Workshop content**

4.1. Objectives

This workshop aims at introducing the R language to non-users by enabling them to make simple data visualizations. People who had previously contacted with R will also benefit from this workshop by refreshing previous concepts and sharing ideas and critical thinking with others. 

At the end of the workshop participants should:
* Understand what is R and it's usage 
* Be able to use specific code and change some of it's arguments to customize the output
* Use a specific dataset, select specific variables and produce a data visualization 

<span style = "color: green">Add PT version</span>


4.2. Scope
A brief introduction to R and to some data visualization associated packages and functions will be given. However, R grammar and syntax will not be covered in detail for this workshop.
Data analysis and data analysis interpretation will be out of the scope for this workshop. This can be covered in a future workshop


4.3. Plano/Programa 


**Para nós**

9h15 - Recepção dos participantes/Welcome

9h30 - Introdução da comunidade R-Ladies Lisboa

9h45 - Sorteio de grupos

10h -  Introdução à visualização de dados

10h05 - Apresentação da base de dados exemplo (de preferencia algo que dê para storytelling)

10h10 - Exercício 1 (desenhar visualização de dados em papel)

10h15 - Iniciar R-Studio - explicação genérica sobre o programa (janelas, output, ajuda, gravar ficheiro)

10h25 - Dicas para Exercício 1 - mostrar código plot e ggplot2

10h30 - Prática - Reprodução do mesmo código - Para quem conseguir fazer, sugestão de alteração de alguns argumentos

11h15 - 11h30 - Cafézinho e Comida! 

11h40 - Exercício 2 - mostrar outro exemplo de código e introduzir 3 exemplos de bases de dados

11h45- Grupos devem escolher 1 tema e produzir 1 visualização

12h - Apresentação de cada grupo (1-2 mins cada)

12h15 - Finalização do workshop e anunciar eventos futuros


**Para os participantes**

9h15 - Recepção - Boas vindas

9h30 - Introdução da comunidade R-Ladies Lisboa

9h45 - Sorteio e formação de grupos

10h -  Introdução à visualização de dados

10h05 - Apresentação de um exemplo de base de dados 

10h15 - Iniciar R-Studio - Breve explicação

10h30 - Exercício 1

11h15 - 11h30 - Cafézinho e Comida! 

11h40 - Exercício 2 

12h00 - Apresentação de cada grupo (1-2 mins cada)

12h30 - Finalização do workshop e anunciar eventos futuros


**Para o meetup**

9h15 - Recepção - Boas vindas

9h30 - Introdução da comunidade R-Ladies Lisboa

10h -  Introdução à visualização de dados

10h30 - Exercícios

11h15 - 11h30 - Cafézinho e Comida! 

11h40 - Exercícios

12h30 - Finalização do workshop 


<span style = "color: green"> **Add english version** </span>


3.4. Content

* Brief intro to R (founders maybe), R syntax (some brief examples to try - see on R Ladies RTP data vis workhop - info on github), base plot and ggplot2
* Data visualization is not data analysis but can be a useful tool for story telling

3.5. Futuros eventos

* Estatística
* Dplyr e manipulação de dados 
* Dúvidas comuns, packages + utilizados (FMV)

